from spider.spider import get_search_results_async,get_custom_info_async
from spider.spider_se import get_search_result_async as searach_for_official_website
from spider.model import translate_goods_async, get_company_intro_async